# Math 542A Homework 10

In [59]:
import numpy as np
import scipy as sp
from scipy.linalg import sqrtm
import scipy.stats

## Problem 10.9

### a)

Store the four sub-matrices of matrix R as variables. We then proceed to calculate the eigenvalues/vectors from the product matrix of inverses and inverse roots. 

In [92]:
R11 = np.matrix([[1,.6328],[.6328,1]])
R12 = np.matrix([[.2412,.0586],[-.0553,.0655]])
R21 = R12.T
R22 = np.matrix([[1,.4248],[.4248,1]])

In [93]:
R11_invrt = sp.linalg.sqrtm(np.linalg.inv(R11))
R22_inv = np.linalg.inv(R22)
R22_invrt = sp.linalg.sqrtm(R22_inv)
R11_inv = np.linalg.inv(R11)

In [98]:
mat_prod = (((R11_invrt.dot(R12)).dot(R22_inv)).dot(R21)).dot(R11_invrt)
mat_prod2 = (((R22_invrt.dot(R21)).dot(R11_inv)).dot(R12)).dot(R22_invrt)

In [99]:
e_val, e_vec = np.linalg.eig(mat_prod)
e_val2, e_vec2 = np.linalg.eig(mat_prod2)

Recall that the canonical correlation values are the square roots of the eiganvalues of the product matrix. 

In [100]:
canonical_corr = np.sqrt(e_val)

In [54]:
a = e_vec.T.dot(R11_invrt)
b = e_vec2.T.dot(R22_invrt)

In [53]:
canonical_corr #respective correlations between U1,V1 and between U2,V2

array([0.39450592, 0.06884787])

In [55]:
a  #coefficients of X(1)

matrix([[ 1.25684474, -1.02531668],
        [ 0.29701768,  0.78524131]])

In [56]:
b  #coefficients of X(2)

matrix([[ 1.10447218, -0.45272158],
        [-0.01818009,  1.00758746]])

### b)

Calculate and compare the test statistic with the chi-square tail.

In [57]:
coeff = -(140-1-.5*(5))

In [64]:
test_stat = coeff * np.log((1-e_val[0])*(1-e_val[1]))
chi = sp.stats.chi2.ppf(.95,4)

In [66]:
(test_stat, chi)

(23.74030112729348, 9.487729036781154)

The test statistic exceeds the chi-square tail, so that we have sufficient evidence to reject the null hypothesis. Hence, at least one component of the correlation vector is nonzero; the next test determines which component that is. 

In [70]:
test_stat2 = coeff*np.log(1-e_val[1])
chi2 = sp.stats.chi2.ppf(.95,1)

In [71]:
(test_stat2, chi2)

(0.6485522224578681, 3.841458820694124)

We fail to reject the second null hypothesis, so that we may reasonably conclude that the first canonical correlation is nonzero. Contextually, this means that overall reading ability does indeed correlate with overall math ability. 

### c)

Calculate the matrices of errors of approximations.

In [96]:
R11-(a[:,0].dot(a[:,0].T) + a[:,1].dot(a[:,1].T))

matrix([[-1.63093301,  1.0646159 ],
        [ 1.0646159 ,  0.29517659]])

In [97]:
R22-(b[:,0].dot(b[:,0].T) + b[:,1].dot(b[:,1].T))

matrix([[-0.42481562,  0.90103599],
        [ 0.90103599, -0.015563  ]])

In [101]:
R12-(canonical_corr[0]*a[:,0].dot(b[:,0].T) + canonical_corr[1]*a[:,1].dot(b[:,1].T))

matrix([[-0.33839143,  0.13874076],
        [-0.16024167,  0.01315787]])

## Problem 10.12

### a)

In [79]:
R11 = np.matrix([[1,.8],[.8,1]])
R12 = R21.T
R21 = np.matrix([[.26,.33],[.67,.59],[.34,.34]])
R22 = np.matrix([[1,.37,.21],[.37,1,.21],[.21,.35,1]])

In [82]:
R11_invrt = sp.linalg.sqrtm(np.linalg.inv(R11))
R22_inv = np.linalg.inv(R22)
R22_invrt = sp.linalg.sqrtm(R22_inv)
R11_inv = np.linalg.inv(R11)

In [83]:
mat_prod = (((R11_invrt.dot(R12)).dot(R22_inv)).dot(R21)).dot(R11_invrt)
mat_prod2 = (((R22_invrt.dot(R21)).dot(R11_inv)).dot(R12)).dot(R22_invrt)

In [84]:
e_val, e_vec = np.linalg.eig(mat_prod)
e_val2, e_vec2 = np.linalg.eig(mat_prod2)

In [86]:
can_corr = np.sqrt(e_val)

In [87]:
can_corr

array([0.69570713, 0.18475722])

We now proceed to conduct the hypothesis test that the problem specifies. 

In [88]:
coeff = -(70-1-.5*(6))
test_stat = coeff * np.log((1-e_val[0])*(1-e_val[1]))
chi = sp.stats.chi2.ppf(.95,6)

In [89]:
(test_stat, chi)

(45.96215294478425, 12.591587243743977)

Hence, the canonical correlation vector is not uniformly zero, so that there exists at least one nonzero canonical correlation. 

In [90]:
chi = sp.stats.chi2.ppf(.95,2)
test_stat = coeff * np.log(1-e_val[1])

In [91]:
(test_stat,chi)

(2.29227534391134, 5.991464547107979)

We conclude that the first canonical correlation is nonzero. 

### b)